server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema.sql
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  messages:
    encoding: UTF-8

  jmx:
    enabled: true

  data:
    rest:
      base-path: book-data-rest

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  health:
    diskspace:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    ROOT: INFO
  file:
    name: "hw16-spring-actuator-log"